version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acebook-app
    overwrite: true

permissions:
  - object: /home/ec2-user/acebook-app
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user