name: CD
run-name: CD Ran by ${{ github.actor }} 

on:
  workflow_run:
    workflows: ['CI']
    types:
        - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Sync files to S3
        run: aws s3 sync ./dirname s3://${{ secrets.AWS_BUCKET }} --delete --no-acl