name: CD
run-name: CD Ran by ${{ github.actor }}
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Debug AWS CLI config
        run: |
          aws --version
          aws configure get default.s3.acl || echo "No default ACL configured"
      - name: Clear default ACL config
        run: aws configure set default.s3.acl ''
      - name: Zip deployment package
        run: |
          zip -r deploy.zip . -x '*.git*' -x '*.github*' -x 'node_modules/*' -x 'deploy.zip'
          # You can add/exclude more patterns as needed
      - name: Upload zip to S3
        run: aws s3 cp deploy.zip s3://${{ secrets.AWS_BUCKET }}/deploy.zip
