name: CD
run-name: CD Ran by ${{ github.actor }} 

on:
  workflow_run:
    workflows: ['CI']
    types:
        - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

