name: CI
run-name: CI Ran by ${{ github.actor }} 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-testing:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install MongoDB
        run: |
            curl -fsSL https://pgp.mongodb.com/server-8.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
            --dearmor
            echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | \
            sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org
            sudo systemctl start mongod
            mongod --version

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Start test server
        run: npm run start:test &

      - name: Run Jest tests
        run: npm test

        
