name: Acebook CI-CD
run-name: ${{ github.actor }} is running CI-CD processes

on:

    push:
        branches: [ main ]
    pull_request:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
        - name: Checkout code
          uses: actions/checkout@v4

    # 2. Setup Node.js (version from README)
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '23'

    # 3. Install dependencies
        - name: Install dependencies
          run: npm ci
        
    # 4. Run linter
        - name: Run ESLint
          run: npm run lint

    # 5. Run tests
        - name: Run Jest tests
          run: npm test
